# Generated by Django 4.2.29 on 2026-05-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credential',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='credential',
            name='password',
            field=models.CharField(max_length=512),
        ),
    ]
